### ISSUE TITLE
npm run docker:build error

### ISSUE THREAD

**Issue by rds80** [PacktPublishing/Angular-6-for-Enterprise-Ready-Web-Applications#1]
I'm on the section "Setting up Docker scripts" and trying to follow the steps using Docker version 18.06.1-ce, build 67f9a391.  I'm using Windows 10 Enterprise Edition.

When I run "npm run docker:build", I get the following error:

unable to prepare context: unable to evaluate symlinks in Dockerfile path: GetFileAttributesEx D:\AngularJS\safari\books\angular6ERWA\local-weather-app\Dockerfile: The system cannot find the file specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! local-weather-app@1.0.0 docker:build: `cross-conf-env docker image build . -t $npm_package_config_imageRepo:$npm_package_version`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the local-weather-app@1.0.0 docker:build script.

Would you be able to provide instructions on how to run the command when using Docker Toolbox?

**Comment by duluca** [comment]
@rds80 Commands between Docker for Windows and Docker Toolbox should be the same. As Docker Toolbox is a legacy product, however there could be environmental issues. Do you use Docker Toolbox for other things? If not please check this article out, or consider upgrading to the latest version https://docs.docker.com/toolbox/toolbox_install_windows/
