### ISSUE TITLE
ng completion mising?

### ISSUE THREAD

**Issue by swforeman0** [PacktPublishing/Angular-6-for-Enterprise-Ready-Web-Applications#2]
Was attempting to add auto-completion functionality to the cli on Git Bash for Windows. (Chapter 2 - page 81 : Configuring Angular CLI autocomplete).  Got error - The specified command ("completion") is invalid. Am I missing a step here. The results of ng -h doesn't list 'completion' as a command either. Did I miss a step?

**Comment by duluca** [comment]
The completion command was removed from the Angular CLI.
